### ISSUE TITLE
Theme colors containing f do not work

### ISSUE THREAD

**Issue by Willem3141** [Caster/Beamer-TUe#19]
Hexadecimal theme colors containing the letter f seem to be misparsed.

````latex
\usetheme[theme=\#0000f0, ...]{tue2008}
````

yields

````
! Missing number, treated as zero.
<to be read again> 
                   f
l.71 \ProcessOptionsBeamer
````

**Comment by Caster** [comment]
Does it work with a capital F?

**Comment by Willem3141** [comment]
Right, why didn't I think of trying that :neutral_face: Thanks!

It is strange, though, that `a` to `e` do work in lowercase, but `f` doesn't...

**Comment by Caster** [comment]
That indeed is strange... So, we pass this to the \definecolor{HTML}{...} method somewhere, I think that is where it might go wrong. I will see - at some point - if converting it to uppercase helps. Good catch :smile:

**Comment by Willem3141** [comment]
I made the example in the README file uppercase, as a temporary fix :smile:

**Comment by Caster** [comment]
So... I was testing this issue again and it seems to have fixed itself. You can try for yourself using the custom-theme example in this repository. Now I did find out that in the meantime, a new version of the xcolor package has come out and I have that one. It is *v2.12* (2016/05/11). Maybe a fix was introduced there? It is not mentioned in the changelog, but that does not really say much. The last update before that one is from 2007, according to the changelog, which makes me believe it must have been the latest update.

**Comment by Willem3141** [comment]
For me this does not work:

![wimiso-mockup-2](https://cloud.githubusercontent.com/assets/7533280/15745966/cb77501e-28d4-11e6-949a-8db317f4c736.png)

But, indeed, I have the old *xcolor* version:

````latex
\ProvidesPackage{xcolor}
 [2007/01/21 v2.11 LaTeX color extensions (UK)]
````
