### ISSUE TITLE
Add HTML color codes to README and site

### ISSUE THREAD

**Issue by Caster** [Caster/Beamer-TUe#20]
For convenience, having the color codes ready for copy and paste is very useful.

**Comment by Willem3141** [comment]
Hmm... the website still isn't updated...

**Comment by Caster** [comment]
You need to update the gh-pages branch ;-)
Op 1 jun. 2016 1:13 p.m. schreef "Willem Sonke" <notifications@github.com>:

**Comment by Caster** [comment]
All is done now.

Most important commits that helped in this:
7981b8c670f2ee3297a065b19d0c57d426f96918 `[ master ]` *Add HTML colours to the README file.*
0a0afff97f44bedba787aadb8e0908c44135dca1 `[ master ]` *Small fixes to README.*
b93866af782803601f2435175a5e651d102f5b49 `[gh-pages]` *Update site, use Jekyll.*
7a738d2f7d3ca92c51732fb8dc1c7a75d0110cc5 `[gh-pages]` *Add a script to update the site contents.*

Future updates to the site should thus be easy :-)
