### ISSUE TITLE
Font install fails on Windows

### ISSUE THREAD

**Issue by omarzd** [Caster/Beamer-TUe#21]
Hello. I'm using Windows 7 x64 and I followed the steps in the readme to the letter. In the end, when I ran `kpsewhich tue.map`, it reported "Sorry, but "MiKTeX Configuration Utility" did not succeed". 

Another issue is that you mention the path `dvips/config/tue.map`, but your `latex_huisstijl.zip` does not include a dvips folder. `tue.map` now resides in `fonts\map\tue.map`.

Thank you

**Comment by Caster** [comment]
Thank you for taking the time to report this! Let's see if we can get this fixed.

Does MiKTeX report any other errors, maybe in a log file? That would be really helpful. Also, did you install MiKTeX yourself, or is this a machine provided by the TU/e?

You are right about the `dvips` directory, I will update the README.

**Comment by omarzd** [comment]
I installed MiKTeX myself. This is not the TU/e-provided machine.
(Pause)
It worked! I just went to check the logs, then redid all the steps. and finally when I did `kpsewhich tue.map`, it returned the font map. I think I just didn't refresh FNDB for the last time. And also, running ` initexmf -u` while the setting window is open will not work. Maybe you should say this in the Readme.

I have one more question. Do I need to keep the entry in Roots for `localtexmf`? and do I need to keep the folder itself?

**Comment by Caster** [comment]
You do need to keep the Roots entry as long as you want to use the fonts. For the same reason, you need to keep the folder itself. If it is in the way: feel free to use any other location! I can probably mention this in the README... `C:\localtexmf` is just an arbitrary path. MiKTeX knows about this path as soon as you add the Roots entry.

I will also mention that the settings window needs to be closed. It probably locks a file somewhere, causing the command line utility to error. Thanks for finding this and reporting back!

**Comment by omarzd** [comment]
The command window *does* indeed lock a file somewhere. I've seen it in the log like so:
```
INFO  initexmf - starting: MiKTeX Configuration Utility (MiKTeX 2.9.6100 64-bit)
FATAL initexmf - Windows API error 32: The process cannot access the file because it is being used by another process.
FATAL initexmf - Info: path="%userprofile%\AppData\Local\MiKTeX\2.9\miktex/data/le\3699db410a98ce51d737438f41f94075.fndb"
FATAL initexmf - Source: Libraries\MiKTeX\Core\File\win\winFile.cpp
FATAL initexmf - Line: 286
```
