### ISSUE TITLE
Mac font installation

### ISSUE THREAD

**Issue by MartinPlantinga** [Caster/Beamer-TUe#23]
I followed the installation font installation instructions for Mac, but it continuously gave an error. I finally achieved a systemwide installation by doing the following:

1. `kpsewhich --var-value TEXMFLOCAL`, this gave me `/usr/local/texlive/texmf-local/`
2. `cp -r /path/to/latex_huisstijl.zip /usr/local/texlive/texmf-local/`.
3. ` cd /usr/local/texlive/texmf-local`
4. `unzip huisstijl.zip`
5. `sudo mktexlsr`
6. `sudo updmap-sys --enable Map=tue.map`
7. `sudo updmap-sys`

Without the last command, it wouldn't install. This post helped me: [Problem using locally installed font](http://tex.stackexchange.com/questions/160766/problem-using-locally-installed-font/236614#236614).

**Comment by Caster** [comment]
Thank you for reporting this! As you can see, I have updated the [documentation](https://caster.github.io/Beamer-TUe/#tue-font-installation) to include the extra `updmap-sys` invocation. Just in case, I also added an extra `updmap` invocation for a single-user installation. I hope this addresses your issue.
